### ISSUE TITLE
Doesn't work for me...

### ISSUE THREAD

**Issue by tas509** [scriptit-fr/ChatGPTApp#14]
<img width="819" alt="Chat_GPT_Demo_-_Project_Editor_-_Apps_Script" src="https://github.com/scriptit-fr/ChatGPTApp/assets/126862771/afc9099c-66a5-4562-9643-0d6c2eae6ed3">

I made an openai key, added this code and got this... 

Any ideas?

**Comment by tas509** [comment]
Execution log
11:46:14 AM	Notice	Execution started
11:46:14 AM	Error	Request failed with response code 401
11:46:14 AM	Error	Failed to fetch the URL after 5 attempts
11:46:14 AM	Info	request failed
11:46:14 AM	Notice	Execution completed

**Comment by keligggg** [comment]
Hi,

Be careful, you use:
`ChatGPTApp.setGoogleSearchAPIKey()`
Instead of :
`ChatGPTApp.setOpenAIAPIKey()`

**Comment by tas509** [comment]
[FACE PALM] ... sorry!

**Comment by RomainVialard** [comment]
Thanks we will add fail safes to better warn the user in case of a misconfiguration

**Comment by GuillemineA** [comment]
We added error messages to warn users if a misconfiguration is detected
