### ISSUE TITLE
Make restrictToWebsite() a method of a Chat instance

### ISSUE THREAD

**Issue by RomainVialard** [scriptit-fr/ChatGPTApp#16]
Not ChatGPTApp.restrictToWebsite("https://support.google.com")
But ChatGPTApp.newChat().enableBrowsing(true).restrictToWebsite("https://support.google.com")

**Comment by GuillemineA** [comment]
Now to restrict browsing to a specific website, you add a second parameter when enabling browsing
```javascript
ChatGPTApp.newChat().enableBrowsing(true);
ChatGPTApp.newChat().enableBrowsing(true, "https://support.google.com/");
```
